[features]
seeds = false
skip-lint = false

[programs.localnet]
reputation = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
escrow = "HmbTLCmaGvZhKnn1ZfaCg8cCrtkS98niKa9DxbEkC6Jk"

[programs.devnet]
reputation = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
escrow = "HmbTLCmaGvZhKnn1ZfaCg8cCrtkS98niKa9DxbEkC6Jk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0"
